services:
  whoami:
    image: traefik/whoami
    container_name: ${WHOAMI_NAME}
    hostname: ${WHOAMI_NAME}
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    networks:
      traefik:
        ipv4_address: ${WHOAMI_IP4} # Static IP
    labels:
      # Orb Stack
      - dev.orbstack.domains=${WHOAMI_SUB_DOMAIN}.orb.local
