services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: ${DOZZLE_NAME}
    hostname: ${DOZZLE_NAME}
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    networks:
      services:
        ipv4_address: ${DOZZLE_IP4} # Static IP
    ports:
      - "${DOZZLE_HTTP_PORT_FORWARD}:${DOZZLE_HTTP_PORT}/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/users.yaml:/app/data/users.yaml:ro # Create Login Credentials
    labels:
      # Orb Stack
      - dev.orbstack.domains=${DOZZLE_SUB_DOMAIN}.orb.local
