services:
  grafana:
    image: grafana/grafana:latest
    container_name: ${GRAFANA_NAME}
    hostname: ${GRAFANA_NAME}
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - "${GRAFANA_HTTP_PORT_FORWARD}:${GRAFANA_HTTP_PORT}/tcp"
    networks:
      services:
        ipv4_address: ${GRAFANA_IP4} # Static IP
    volumes:
      - ./data/grafana-storage:/var/lib/grafana
    labels:
      # Orb Stack
      - dev.orbstack.domains=${GRAFANA_SUB_DOMAIN}.orb.local

volumes:
  grafana-storage:
